openSUSE/get-o-o

_data/152.yml

Add aarch64 Live ISO for Leap 15.2

---

_data/locales/en.yml

add "gamers" to tumbleweed p1

---

Rakefile
_data/153.yml

* Also fetch file sizes for Leap 15.3
* Add XFCE-Live to 15.3 download page

Leap 15.3 improvements

---

_includes/overview/Tumbleweed.html

Let's is a contraction, meaning "let us." Lets is the proper word here.

Fixed typo

---

_data/locales/ar.yml
_data/locales/bg.yml
_data/locales/ca.yml
_data/locales/cs.yml
_data/locales/de.yml
_data/locales/el.yml
_data/locales/en.yml
_data/locales/es_419.yml
_data/locales/fr.yml
_data/locales/gl.yml
_data/locales/hi.yml
_data/locales/id.yml
_data/locales/it.yml
_data/locales/ja.yml
_data/locales/nb.yml
_data/locales/pl.yml
_data/locales/pt.yml
_data/locales/pt_BR.yml
_data/locales/sk.yml
_data/locales/zh-CN.yml
_data/locales/zh_HK.yml
_data/locales/zh_TW.yml

Change copyright from 2020 into 2021

---

_includes/features/desktops.html
index.html

This is a fix for issue #59 Also added was matamo code. @hellcp could you take a look at merge

fix for issue #59 

---

_data/153.yml
_data/locales/en.yml
_data/tumbleweed.yml

Question: <s>Is there a script/command to sync new strings in `en.yml` to other locales?</s> Answered!

Add information about Arm JeOS images

---

_data/releases.yml

Let's aim for availability at 12:00 on 2nd March (Wednesday)

Bump for 15.4 Beta on 2nd March

---

_data/releases.yml

Updated the 15.2 and 15.1 states to 'EOL' in the releases.yml file

 akshat5302 patch 1

---

_data/153.yml
_data/154.yml
_data/locales/en.yml
_data/tumbleweed.yml
_includes/distribution.html

Update notes about live images

---

_data/leap.yml

(let's wait with the merge once the build is published eta something like 2h)

Leap 15.4 RC is today

---

_data/leapmicro.yml
index.html
leapmicro.html

Leap Micro 5.2 GA is today

---

_data/154.yml

Let's keep our torrent offering consistent

consistency: Add torrents for all non-intel arches

---

_data/155.yml
_data/leap.yml

Looks good, I had a glitch with 15.4 being hidden, but seems like that was cause by premature setting of the EOL future date.
Current setup looks good

add 15.5 poo#113911

---

_data/53.yml
_data/leapmicro.yml

Let's make quick Beta availability on top of SLE Micro 5.3 RC1

add leap_micro 5.3

---

_data/microos.yml

this flavor no longer exists.
Fixes #114

Drop k3s MicroOS flavor

---

desktop.html
server.html

Fix query and hash not appended in leap on server and desktop pages

---

_data/154.yml
_data/locales/en.yml

* Continuously re-built DVD with all released updates
* Replaces quarterly update images for Leap.

Updated media for Leap 15.4

---

_data/154.yml
_data/leapmicro.yml

Set date for Micro 5.3 RC and GA

Leap Micro 5.3 RC + GA date

---

_data/locales/en.yml
_data/tumbleweed.yml

Fixes: #125
Signed-off-by: Michal Suchanek <msuchanek@suse.de>

Add ppc64 download link for tumbleweed.

---

_data/leapmicro.yml

* let's aim for marketing annoucement today at noon as I'm just publishing bits

Revert leapmicro53 back to beta

---

_data/154.yml
_data/tumbleweed.yml

After spotting download issue in https://github.com/openSUSE/get-o-o/pull/123

Revert Minimal-VM to JeOS for now

---

_data/leap.yml

Beta availabilility is expected next Tuesday 12:00 UTC

Bump for 15.5 Beta poo#113911

---

_data/54.yml
_data/leapmicro.yml

Screenshots, I've tested links all seem to work

Leap Micro 5.4 Enters Alpha with build 11.16

---

_data/leapmicro.yml

Related annoucement https://github.com/openSUSE/news-o-o/commit/2aa9a6204d8f6d1bdd1bd11096f474a8e4fa80eb

Leap Micro 5.4 Beta is tomorrow

---

_data/155.yml

re-enable torrent links for 15.5 GA

---

_includes/verify_download.html

Resolves https://github.com/openSUSE/get-o-o/issues/155.

Update signing key

---

_data/156.yml
_data/leap.yml

Initial config,
local build fails on hashes. Do not merge until I resolve it.

Add 15.6 to get-o-o poo#131651

---

_data/locales/en.yml
_includes/choosing_media.html
_includes/documentation.html
_includes/overview/LeapMicro.html
assets/css/software.css

LeapMicro tweaks

---

_data/55.yml
_data/leapmicro.yml

Leap Micro 5.5 Alpha Availability

Mark Leap Micro 5.5 as Alpha

---

_data/leapmicro.yml

GA is tomorrow, 5.3 is automatically EOL

LeapMicro 5.5 GA, 5.3 EOL

---

_config.yml

Happy new year, added 2024 instead of 2023 in copyright

2024 new year

---

_data/locales/en.yml
server.html

This should hopefully fix the links per @hellcp 's suggestion in #174

Fix mistyping of site.release.leap_micro

---

_data/locales/en.yml

Any feedback is highly appreciated.

Update text for Micro 6.0+

---

_includes/logos/leap.svg

Update leap 15.6 logo

---

_data/locales/en.yml
_includes/choosing_media.html

* Agama media section for Leap 16.0

Add agama-only section for Leap 16.0 install media choice

---

_data/160.yml

* Disable torrent links for Leap 16.0 until GM

Disable torrents until GM boo#1231361

---

_data/leapmicro.yml

Let's aim for beta availability tomorrow. I'd like to record and publish a migration video with some small post on news-o-o.

Make Leap Micro 6.1 Beta availability tomorrow

---

README.md

This is useful especially if you do development in distrobox etc.

Improve docs for starting from scratch

---

_data/62.yml
_data/leapmicro.yml

Micro 6.2 GA together with 16.0
