openSUSE/get-o-o

_data/releases.yml
Setting tomorrow as a release day for Beta
The build will be 91.1 https://openqa.opensuse.org/tests/overview?distri=opensuse&version=15.3&build=91.1&groupid=50
15 SP3 Public Beta recieved go as well and will go live today.
=> Leap 15.3 Beta release day is tomorrow poo#76324

_includes/documentation.html
Relates to poo#76135 and source offer in general
I did want to re-use translated string source_code. Otherwise I'd reference "How to get source code".
=> Add reference for the source code offer Issue #27 and #11

_data/releases.yml
* A week after the submission deadline 21.4
* https://en.opensuse.org/openSUSE:Roadmap
Let's merge it once we have a build that looks okay.
=> Leap 15.3 RC date set to 28.4.2021

_data/153.yml
While /live/ still exists, it's only a redirect which breaks quite often.
Fixes #34
(CC @lkocman)
=> Use /distribution/leap/15.3/appliances/iso/ for 15.3 live isos

_data/locales/ca.yml, _data/locales/de.yml, _data/locales/en.yml, _data/locales/es.yml, _data/locales/fr.yml, _data/locales/it.yml, _data/locales/ja.yml, _data/locales/pt_BR.yml, _data/locales/sk.yml, _data/locales/zh-CN.yml, _data/locales/zh_TW.yml, _includes/distribution.html
https requests are now properly redirected to a suitable https mirror,
because https requests for images are now handled by MirrorCache
=> Remove chrome_warning

_data/154.yml, _data/releases.yml
We've changed -Current to -Media symlinks for 15.4 images.
Appliances and Live is yet to be confirmed, meanwhile keeping the old links. 
Related appliances and live P. ftp structure for appliances/live is yet empty. 
https://github.com/openSUSE/publish_distro/pull/18
=> Make Leap 15.4 testing visible poo#99930

_data/locales/ca.yml, _data/locales/cs.yml, _data/locales/de.yml, _data/locales/en.yml, _data/locales/es.yml, _data/locales/fr.yml, _data/locales/id.yml, _data/locales/it.yml, _data/locales/ja.yml, _data/locales/pl.yml, _data/locales/pt_BR.yml, _data/locales/ru.yml, _data/locales/sk.yml, _data/locales/sv.yml, _data/locales/zh-CN.yml, _data/locales/zh_TW.yml
IBM has changed the name of the s390x architecture because of the Ukraine war. We have to replace IBM Z with IBM zSystems everywhere.
=> Replace IBM Z with IBM zSystems

_data/tumbleweed.yml
For TW there are missing ability to choose mirror in get-o-o.
I added this.
**Before:** 
**After:**
=> Add missing pick_mirror links for TW Live Images

_data/leapmicro.yml
Bump to RC with Build24.2, only minor tweaks to EOL date (correction)
=> Leap Micro 5.4 RC build is out

_data/leap.yml, _data/leapmicro.yml
Leap Micro 5.4 GA, 5.2 is EOL, Leap 15.5 enters RC phase
IPRQ approval for Micro was received today (same id as SLEM 5.4).
=> Leap Micro 5.4 GA, 5.2 is EOL, Leap 15.5 enters RC phase

_data/leap.yml
Leap 15.5 marketing availability is next week on Wednesday. GM is already confirmed, we can publish build any time to make sure mirrors have it synced.
https://progress.opensuse.org/issues/114208
=> Leap 15.5 marketing availability is at 12:00 UTC 7th June 2023 poo#114208

_data/155.yml
I don't get any seeders for the NET installers for ppc64le and s390x, but I have been able to download the others.
=> Add torrent links for the Leap 15.5 release

_data/locales/en.yml
The `cloud_images` key was missing from the English locales of MicroOS's `Download` section in https://get.opensuse.org/microos/. This PR adds the key to make the page render nicely.
**Before (without the key)**
**After (with the key)**
=> Add missing `cloud_images` key in MicroOS page

_data/55.yml, _data/locales/en.yml
Adding qcow aarch64/x86_64 images.
Any suggestions for description are welcome.
TBH Perhaps we can just skip get-o-o and leave them on download-o-o if somebody needs them.
=> Handling for LeapMicro 5.5 raw and qcow image texts

_data/leapmicro.yml
let's aim for today 12:00
Roadmap was updated https://en.opensuse.org/openSUSE:Roadmap#Schedule_for_openSUSE_Leap_Micro_5.5
=> Leap Micro 5.5 is RC

_data/locales/en.yml, server.html
Possibly fixes #101 
Big disclaimer: I didn't actually get the Ruby environment to work, so this is entirely untested
But since Leap Micro has been missing from the distros in the server overview for quite some while, I thought I'd try anyway. I basically just copied the Leap section of server.html and replaced all mentions of leap with leapmicro and added some descriptions to locale that are mostly pulled from recent openSUSE news articles about Leap Micro.
Maybe a maintainer is willing to test it to see if it works, maybe someone else interested in working on it can use it as a starting point, or maybe it's just gonna get rejected outright, which is also fine with me. Was just a bit bugged Leap Micro still isn't on there and thought I'd try doing what I can with it.
=> Add Leap Micro to server distros

_data/55.yml
The primary_link for the aarch64 preconfigured_qcow_image was linked to an x86_64 image.
This pull request changes that line to the correct aarch64 image.
Closes: #177
=> fix: wrong primary_link for a leap micro aarch64 image

_data/leap.yml
* Live event at 21:00 CET at https://calendar.opensuse.org/teams/marketing/events/thursday_weekly_meeting
=> Leap 15.6 Availability tomorrow at usual time

_data/locales/en.yml
Changed the EN translation for `site_copyright` from `© 2023 openSUSE contributors` to `© 2024 openSUSE contributors`.
=> Update copyright year for EN locale.

_data/leap.yml
* Set EOL dates for 15.4 (already EOL) and 15.5 (Dec 31)
=> Add 12th June as release day for Leap 15.6

_data/60.yml, _data/leapmicro.yml
* add updated links for Packages dvd after to match new productcomposer
* Set beta release day to today (Beta build is already on the way)
=> Leap Micro 6.0 Beta

_data/microos.yml, _data/tumbleweed.yml
* Unblock CI especially for for Leap 16.0 addition
* OBS/downlad-o-o servers vmdk files without the .xz suffix, I suppose somebody changed kiwi image build configuration.
```
Checking image size for /ports/aarch64/tumbleweed/iso/openSUSE-Tumbleweed-Rescue-CD-aarch64-Current.iso
Start the website tests
The following files are reporting 0 size from the repos:
/tumbleweed/appliances/openSUSE-MicroOS.x86_64-VMware.vmdk.xz
/tumbleweed/appliances/openSUSE-MicroOS.x86_64-ContainerHost-VMware.vmdk.xz
/tumbleweed/appliances/openSUSE-Tumbleweed-Minimal-VM.x86_64-VMware.vmdk.xz
Error: Process completed with exit code 1.
```
Full Error log:
https://github.com/openSUSE/get-o-o/actions/runs/11135620517/job/30946172862?pr=217
=> Do not use xz compression for VMDKs on MicrOS and TW

_site/index.html
closes https://github.com/openSUSE/get-o-o/issues/213
The github source link will now open in new tab. By using the target attribute in HTML I have solved the problem.
=> Fixes link redirection problem of Github

_data/locales/en.yml
A minor correction - adviced changed to advised
https://github.com/openSUSE/get-o-o/blob/cc72f0bc414e65026d3f228030941cb2f40e8f49/_data/locales/en.yml#L108
=> Fix spelling mistake in en.yml

_data/160.yml
=> Leap 16.0 image flavor was changed to Leap

_data/locales/en.yml, _data/tumbleweed.yml
=> Tumbleweed: Do not link to ppc64 images

_data/leapmicro.yml
Today is the day ;-) Let's release it before first SLE Micro 6.1 maintenance updates get released.
=> DO NOT MERGE Mark Leap Micro 6.1 as stable

_includes/logos/leap.svg, assets/images/logos/leap.svg
I checked in chromium and firfox browser, on both phone and laptop, but did not find anything wrong with leap.svg. So I simplified the code by removing namespaces and empty <defs> tag.
=> Simplify leap.svg

_data/locales/en.yml
Changed the EN translation for `site_copyright` from `© 2024 openSUSE contributors` to `© 2025 openSUSE contributors`.
=> Update copyright year (from 2024 to 2025) for EN locale

_data/160.yml
Reverts openSUSE/get-o-o#252 issue https://bugzilla.suse.com/show_bug.cgi?id=1242116 is already fixed.
=> Revert "Disable offline media temporarily"

_data/160.yml
* Tested locally
New localtion (the offline dir will likely be renamed later)
https://download.opensuse.org/distribution/leap/16.0/offline/Leap-16.0-online-installer-x86_64.install.iso
=> New Leap 16.0 online image paths

_data/leap.yml
=> Leap 16.0 RC is today

_data/microos.yml
I noticed these were missing, but they were provided on https://en.opensuse.org/Portal:MicroOS/Downloads, which is linked from https://microos.opensuse.org/.
Here's a screenshot of the changes:
=> Add MicroOS OpenStack images
